# Generated by Django 3.1 on 2021-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avator',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
