# Generated by Django 3.1 on 2021-01-13 11:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('animeval', '0002_profilemodel_avator'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='character_voice',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=['None'], max_length=126, size=6),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='corporation',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='started',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
