# Generated by Django 3.1 on 2021-01-15 12:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('animeval', '0003_auto_20210113_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessreview',
            old_name='access_name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='animemodel',
            old_name='anime_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='anime_title',
            new_name='anime',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='evaluation_value_ave',
            new_name='evaluation_ave',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='nickname',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='animemodel',
            name='anime_genre',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='genre_counter',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='anime_genre',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='evaluation_value',
        ),
        migrations.AddField(
            model_name='animemodel',
            name='genre',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='counter',
            name='counter',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=[0, 0, 0, 0, 0, 0, 0, 0], size=8),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='evaluation',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=[0, 0, 0, 0, 0], size=5),
        ),
    ]
